### PR TITLE
[APR] top apr pools chart

### PR DESCRIPTION
**Pull request by Rawallon**
Added chart for top pools, I'm kinda stuck on how are we going to share the pool data without refetch at every component that needs it. I think the simpler answer is just to have a parent component hold all that data and just pass it as prop, however I'd like to know how you guys would go about it.

image

Also, I found that visualing customizing Plotly is very annoying and require some workarounds (eg: [Making the bars end round](https://gist.github.com/mebaysan/80d6c3974d7700b8e6f3a8dca8ccdd03))

### CODE REVIEW

**Review by ribeirojose — DISMISSED** [review]
lgtm. is the other chart with a pool historical performance across rounds also going to be included here or is there another task for it?

**Comment by luizakp** [comment]
> t with a pool historical performance across rounds

I guess it is another task. [Here](https://linear.app/bleu-llc/issue/BAL-639/historical-apr-chart)

**Comment by Rawallon** [comment]
Hey @luizakp, Need your approval to be able to merge

Also, did u mean to remove the comments?

**Comment by luizakp** [comment]
> Hey @luizakp, Need your approval to be able to merge
> 
> Also, did u mean to remove the comments?

Yes! Moved them into an issue so we don't have a bunch of comments laying around being easy to forget. The issue is [here](https://linear.app/bleu-llc/issue/BAL-649/populate-top-pool-chart-with-real-data)

**Comment by luizakp** [comment]
rn the chart is looking like this:

image

we can choose a better selection of colors xD

**Comment by ribeirojose** [comment]
LGTM 👍

**Comment by ribeirojose** [comment]
> rn the chart is looking like this:
> 
> image
> we can choose a better selection of colors xD

I love the Radix colors docs -- maybe this helps! https://www.radix-ui.com/colors/docs/palette-composition/composing-a-palette

**Pull request merged**
